server:
  port: 9010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/razorpay-merchant-db

jwt:
  secret-key: dont-use-in-prodqwertyuioplkjhgfdsxcvbnmghjk

webhook:
  secret-encryption-keys: jEbSy97ac+f1IDJCbVEM0Z4CJ2VzScYQlJWrkxwyVWs=
